apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
spec:
  host: frontend.kt-mvp.duckdns.org
  port:
    targetPort: frontend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: frontend
    weight: 100    
  wildcardPolicy: None  
